### ISSUE TITLE
Using Transforms

### ISSUE THREAD

**Issue by thetutlage** [caleb/broccoli-fast-browserify#1]
What about using transforms ?

**Comment by caleb** [comment]
I haven't used browserify transforms much, since I'm using broccoli, but this is something that might make sense to add to `broccoli-fast-browserify`.

When I get time I'll check it out, it might be pretty easy to add.

**Comment by chmanie** [comment]
That'd be nice!

**Comment by caleb** [comment]
Thanks for your work on this @chmanie!
