### ISSUE TITLE
Custom third party import

### ISSUE THREAD

**Issue by Globegitter** [caleb/broccoli-fast-browserify#9]
I am just playing around to use broccoli + browserify + babelify instead of our current custom build system (also using browserify and babel). We have some custom 3rd party imports such as `import React from '//third_party/js/react';` How can I tell browserify where to look for these modules?

**Comment by Globegitter** [comment]
Ah,  I think I found a way, by just using a custom transform function.

**Comment by caleb** [comment]
You should be able to import modules from NPM:

``` javascript
import React from 'react'
```

As long as react is in your `package.json` file it should work...

Do you mean that you want to keep your custom paths without changing them (e.g. the double foward slashes)?

**Comment by Globegitter** [comment]
I did manage to fix our custom solution via an additional transform - thanks for the quick reply.
